name: Haskell CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Cache
        uses: actions/cache@v3
        env:
          cache-name: cache-cabal
        with:
          path: ~/.cabal
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - uses: haskell/actions/setup@v2
        with:
          ghc-version: "9.2"
          cabal-version: "3.6"

      - uses: haskell/actions/hlint-setup@v2
      - uses: haskell/actions/hlint-run@v2
        with:
          path: ./
          fail-on: warning

      - name: Install dependencies
        run: |
          cabal build --only-dependencies --enable-tests --enable-benchmarks

      - name: Build
        run: cabal build --enable-tests --enable-benchmarks all

      - name: Run ShipGuesser
        run: cabal run shipguesser

      - name: Run ShippGuesser FindInitialGuess
        run: cabal run shipguesser-fig
